In [1]:
#@title Cargando la base de datos
import pandas as pd

path='D:\ITM-------WORKSPACE\Visualizacion_de_Datos\incidentes_viales.csv'

dta=pd.read_csv(path)
dta.head(5)

C:\Users\ignac\AppData\Local\Temp\ipykernel_5164\618908713.py:6: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  dta=pd.read_csv(path)

,AÑO,CBML,CLASE_ACCIDENTE,DIRECCION,DIRECCION ENCASILLADA,DISEÑO,EXPEDIENTE,FECHA_ACCIDENTE,FECHA_ACCIDENTES,GRAVEDAD_ACCIDENTE,MES,NRO_RADICADO,NUMCOMUNA,BARRIO,COMUNA,LOCATION,X,Y
0,2015,1013,Caida Ocupante,CR 46 CL 43,CR 046 043 000 00000,Tramo de via,A000259731,21/10/2015 05:58:00,2015-10-21T10:58:00.000Z,Con heridos,10,1508668,10,Barrio Colón,La Candelaria,"[-75.5688011014, 6.24312304123]",834949.69,1182357.34
1,2015,1020,Choque,CR 43 A CL 29,CR 043 A 029 000 00000,Tramo de via,A000261725,05/11/2015 03:00:00,2015-11-05T08:00:00.000Z,Solo daños,11,1510621,10,San Diego,La Candelaria,"[-75.5693883283, 6.22870030622]",834880.17,1180762.02
2,2015,0205,Otro,CR 46 CL 37,CR 046 037 000 00000,Tramo de via,A000259739,21/10/2015 07:40:00,2015-10-21T12:40:00.000Z,Con heridos,10,1508691,02,La Francia,Santa Cruz,"[-75.5503911403, 6.29869502502]",837004.94,1188499.17
3,2015,0101,Atropello,CR 34 CL 112,CR 034 112 000 00000,Tramo de via,A000259752,21/10/2015 12:00:00,2015-10-21T17:00:00.000Z,Con heridos,10,1508694,01,Santo Domingo Savio No. 1,Popular,"[-75.5442195069, 6.30019383306]",837688.53,1188663.05
4,2015,1504,Choque,CR 50 CL 14,CR 050 014 000 00000,Tramo de via,A000259949,03/11/2015 06:16:00,2015-11-03T11:16:00.000Z,Solo daños,11,1510634,15,Santa Fé,Guayabal,"[-75.578180998, 6.21699243701]",833903.11,1179469.60

In [2]:
dta.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270765 entries, 0 to 270764
Data columns (total 18 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   AÑO                    270765 non-null  object
 1   CBML                   252609 non-null  object
 2   CLASE_ACCIDENTE        270759 non-null  object
 3   DIRECCION              270765 non-null  object
 4   DIRECCION ENCASILLADA  270374 non-null  object
 5   DISEÑO                 269617 non-null  object
 6   EXPEDIENTE             270655 non-null  object
 7   FECHA_ACCIDENTE        270765 non-null  object
 8   FECHA_ACCIDENTES       270765 non-null  object
 9   GRAVEDAD_ACCIDENTE     270765 non-null  object
 10  MES                    270765 non-null  int64
 11  NRO_RADICADO           270760 non-null  object
 12  NUMCOMUNA              270765 non-null  object
 13  BARRIO                 251759 non-null  object
 14  COMUNA                 257967 non-null  object
 15  LOCATION               270765 non-null  object
 16  X                      270765 non-null  float64
 17  Y                      270765 non-null  float64
dtypes: float64(2), int64(1), object(15)
memory usage: 37.2+ MB

***<h3> Estudio de Fecha y Hora del accidente: </h3>***

 ***La siguiente Warning nos recomienda ver la columna 0 debido a que tiene una combinacion de Types:***

 </small>`//DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  dta=pd.read_csv(path)`</small>

In [3]:
dta['AÑO'].unique()

array(['2015', '2014', '2016', '2017', '2018', '2019\\r', '2019', '2020',
       2020, 2015, 2014, 2016, 2017, 2018], dtype=object)

</small> Podemos ver que la columna tiene variables tipo str, int en particual '2019\\r' es distinta. Aunque la solucion seria normalizar estos valores no se procedera debido aq ue se eliminara la columa entera </small>

In [4]:
dta = dta.drop(columns=['AÑO', 'MES', 'FECHA_ACCIDENTES'])

</small> La decision fue tomada debido a que esa misma informacion se encuetra en una sola columna llamada: ***FECHA_ACCIDENTE***</small>

In [5]:
#Funcion para aplicar funciones a mis columnas
lista_columnas = dta.columns.tolist()
def aplicar_a_columnas(df, columnas, funcion):
    resultados = {}
    
    for col in columnas:
        try:
            resultados[col] = funcion(df[col])
        except Exception as e:
            resultados[col] = f"Error: {e}"
    
    return resultados

In [6]:
#Veamos los nulos de cada columna
resultado = aplicar_a_columnas(dta, dta.columns, lambda col: col.isna().sum())
for k, v in resultado.items():
    print(f"'{k}': {int(v)}")

'CBML': 18156
'CLASE_ACCIDENTE': 6
'DIRECCION': 0
'DIRECCION ENCASILLADA': 391
'DISEÑO': 1148
'EXPEDIENTE': 110
'FECHA_ACCIDENTE': 0
'GRAVEDAD_ACCIDENTE': 0
'NRO_RADICADO': 5
'NUMCOMUNA': 0
'BARRIO': 19006
'COMUNA': 12798
'LOCATION': 0
'X': 0
'Y': 0

In [6]:
#Veamos quesi queremos una columna de identificacion del # de caso del accidente el NRO_RADICANDO es el mejor. Se eliminara la columna EXPEDIENTE
print(f"Estos son todos los distintos de NRO_RADICADO: {dta['NRO_RADICADO'].nunique()} y estos lo de EXPEDIENTE: {dta['EXPEDIENTE'].nunique()} ")
dta = dta.drop(columns=['EXPEDIENTE'])

Estos son todos los distintos de NRO_RADICADO: 270730 y estos lo de EXPEDIENTE: 270152

***NOTA:*** Debido a que ***FECHA_ACCIDENTE*** no contiene nulos se intento convertir la info en Datetime no me percate de que el contenido puede ser distienot de un nulo y de un datetime como por ejemplo basura

In [7]:
dta['FECHA_ACCIDENTE'] = pd.to_datetime(
    dta['FECHA_ACCIDENTE'],
    errors='coerce',   # coerse nos va a convertir directamente esa basura a NaT (Not a time)
    dayfirst=True
)

In [ ]:
print(dta['FECHA_ACCIDENTE'].isna().sum())   #Se perderian tan solo 6 registros. Eso es menos del 1% de la informacion. Se borran los nulos
dta = dta.dropna(subset=['FECHA_ACCIDENTE'])

dta['FECHA_ACCIDENTE'].dtype

dtype('<M8[ns]')

***<h3> Estudio de Ubicacion del Accidente : </h3>***

***Analisis Ubicacion:***  Al hacer una debida inspeccion se noto que los valores de ***LOCATION*** oscilan al rededos de los [-75, 6] valores de coordenadas geogrficas de colombia mas en especifico medellin por lo que estos valores corresponden a valores exatos de ubicacion. Para una mayor precision y despues de investigar, los valores que aparecen como X , Y son valores de coordenadas cartesianas que usan ingenieros, topografos y la Alcaldia de Medellín en sus mapas oficiales para referenciar ubicaicones exactas en metros con respecto a cierto origen cuyo ubicacion es conocida.

In [11]:
#Para facilitar el estudio y en terminos mas generales se eliminara esta informacion de ubicacion exacta del accidente de esa manera hacer un estudio por zonas de medellin
dta = dta.drop(columns=['LOCATION', 'X', 'Y','DIRECCION ENCASILLADA'])
dta = dta[[
    'FECHA_ACCIDENTE',
    'NRO_RADICADO',
    'CLASE_ACCIDENTE',
    'GRAVEDAD_ACCIDENTE',
    'DISEÑO',
    'DIRECCION',
    'BARRIO',
    'COMUNA',
    'NUMCOMUNA',
    'CBML'
]]
dta.head()

,FECHA_ACCIDENTE,NRO_RADICADO,CLASE_ACCIDENTE,GRAVEDAD_ACCIDENTE,DISEÑO,DIRECCION,BARRIO,COMUNA,NUMCOMUNA,CBML
0,2015-10-21 05:58:00,1508668,Caida Ocupante,Con heridos,Tramo de via,CR 46 CL 43,Barrio Colón,La Candelaria,10,1013
1,2015-11-05 03:00:00,1510621,Choque,Solo daños,Tramo de via,CR 43 A CL 29,San Diego,La Candelaria,10,1020
2,2015-10-21 07:40:00,1508691,Otro,Con heridos,Tramo de via,CR 46 CL 37,La Francia,Santa Cruz,02,0205
3,2015-10-21 12:00:00,1508694,Atropello,Con heridos,Tramo de via,CR 34 CL 112,Santo Domingo Savio No. 1,Popular,01,0101
4,2015-11-03 06:16:00,1510634,Choque,Solo daños,Tramo de via,CR 50 CL 14,Santa Fé,Guayabal,15,1504

In [17]:
dta['COMUNA'].unique()

array(['La Candelaria', 'Santa Cruz', 'Popular', 'Guayabal', 'El Poblado',
       'Laureles Estadio', 'Robledo', 'Doce de Octubre', 'Aranjuez',
       'Buenos Aires', 'Castilla',
       'Corregimiento de San Antonio de Prado', nan, 'San Javier',
       'Villa Hermosa', 'Belén', 'Manrique', 'La América',
       'Corregimiento de Altavista', 'Corregimiento de San Cristóbal',
       'Corregimiento de Santa Elena', 'In', 'SN', 'No Georef',
       'Corregimiento de San Sebastián de Palmitas', 'Bel\\xE9n',
       'La Am\\xE9rica', 'Corregimiento de San Crist\\xF3bal',
       'Corregimiento de San Sebasti\\xE1n de Palmitas', 'Sin Inf', '0',
       'AU'], dtype=object)

In [ ]:
map_comuna = {
    # Comunas
    'La Candelaria': 'La Candelaria', #10
    'Santa Cruz': 'Santa Cruz', #2
    'Popular': 'Popular', #1
    'Guayabal': 'Guayabal',#4
    'El Poblado': 'El Poblado', #5 
    'Laureles Estadio': 'Laureles–Estadio', #6
    'Robledo': 'Robledo', #7
    'Doce de Octubre': 'Doce de Octubre', #8
    'Aranjuez': 'Aranjuez',#9
    'Buenos Aires': 'Buenos Aires', #
    'Castilla': 'Castilla', #11
    'San Javier': 'San Javier', #12
    'Villa Hermosa': 'Villa Hermosa', #13
    'Belén': 'Belén', #14 
    'Manrique': 'Manrique',#15
    'La América': 'La América', #16

    # problemas de encoding
    'La Am\\xE9rica': 'La América',
    'Bel\\xE9n': 'Belén',
    'Corregimiento de San Crist\\xF3bal': 'San Cristóbal',
    'Corregimiento de San Sebasti\\xE1n de Palmitas': 'San Sebastián de Palmitas',

    # Corregimientos
    'Corregimiento de San Antonio de Prado': 'San Antonio de Prado', #80
    'Corregimiento de Altavista': 'Altavista',#70
    'Corregimiento de San Cristóbal': 'San Cristóbal', #60
    'Corregimiento de Santa Elena': 'Santa Elena', #90 
    'Corregimiento de San Sebastián de Palmitas': 'San Sebastián de Palmitas' #50
}

In [22]:
dta['COMUNA'] = dta['COMUNA'].map(map_comuna)

In [ ]:
#Despues del mapeo nos damos cuenta que la cantidad de nulos supera el 10% de los datos una cantidad considerable por lo que se va a obtar por implementar una estrategia para mejorar este dato
dta['COMUNA'].isna().sum()

np.int64(19860)

In [24]:
map_dir_comuna = (
    dta.dropna(subset=['COMUNA'])
       .groupby('DIRECCION')['COMUNA']
       .first()
)

In [25]:
dta['COMUNA'] = dta['COMUNA'].fillna(
    dta['DIRECCION'].map(map_dir_comuna)
)

In [26]:
dta['COMUNA'].isna().sum()

np.int64(15573)

In [27]:
dta['NUMCOMUNA'].unique()

array(['10', '02', '01', '15', '14', '11', '07', '06', '04', '09', '05',
       '80', 'Sin Inf', '13', '08', '16', '03', '12', '70', '60', '90',
       'In', 'SN', '0', '50', 'AU', '5', '7', '9', '4', '3', '1', '2',
       '8', '6'], dtype=object)

In [38]:
map_numero_comuna = {
    #Comunas
    '1': 1, '01': 1,
    '2': 2, '02': 2,
    '3': 3, '03': 3,
    '4': 4, '04': 4,
    '5': 5, '05': 5,
    '6': 6, '06': 6,
    '7': 7, '07': 7,
    '8': 8, '08': 8,
    '9': 9, '09': 9,
    '10': 10,
    '11': 11,
    '12': 12,
    '13': 13,
    '14': 14,
    '15': 15,
    '16': 16,

    # Corregimientos
    '50': 50,
    '60': 60,
    '70': 70,
    '80': 80,
    '90': 90
}

In [39]:
dta['NUMCOMUNA'] = dta['NUMCOMUNA'].map(map_numero_comuna)
print(dta['NUMCOMUNA'].isna().sum())

20125

In [36]:
dta.loc[dta['NUMCOMUNA'] == '10']

,FECHA_ACCIDENTE,NRO_RADICADO,CLASE_ACCIDENTE,GRAVEDAD_ACCIDENTE,DISEÑO,DIRECCION,BARRIO,COMUNA,NUMCOMUNA,CBML
0,2015-10-21 05:58:00,1508668,Caida Ocupante,Con heridos,Tramo de via,CR 46 CL 43,Barrio Colón,La Candelaria,10,1013
1,2015-11-05 03:00:00,1510621,Choque,Solo daños,Tramo de via,CR 43 A CL 29,San Diego,La Candelaria,10,1020
7,2015-11-04 04:46:00,1510650,Choque,Solo daños,Tramo de via,CR 57 CL 44,La Alpujarra,La Candelaria,10,1009
8,2015-10-21 07:00:00,1508766,Choque,Con heridos,Tramo de via,CL 57 CR 46,Villa Nueva,La Candelaria,10,1018
11,2015-10-22 06:20:00,1508822,Choque,Con heridos,Interseccion,CL 34 CR 48,Perpetuo Socorro,La Candelaria,10,1012
...,...,...,...,...,...,...,...,...,...,...
270734,2017-04-18 16:00:00,1578669,Choque,Solo daños,Interseccion,CR 39 CL 59 A,Los Ángeles,La Candelaria,10,1017
270735,2017-03-07 10:50:00,1573390,Atropello,Con heridos,Tramo de via,CR 46 CL 53,La Candelaria,La Candelaria,10,1019
270746,2017-03-08 10:00:00,1573707,Caida Ocupante,Con heridos,Lote o Predio,CR 45 CL 55,Villa Nueva,La Candelaria,10,1018
270750,2017-04-20 14:55:00,1579348,Choque,Solo daños,Puente,CL 58 CR 62,El Chagualo,La Candelaria,10,1004
270759,2017-03-10 15:15:00,1573960,Choque,Solo daños,Tramo de via,CR 46 CL 50,La Candelaria,La Candelaria,10,1019

In [40]:
map_num_to_comuna = dta.dropna(subset=['COMUNA', 'NUMCOMUNA']) \
    .drop_duplicates('NUMCOMUNA') \
    .set_index('NUMCOMUNA')['COMUNA'].to_dict()

map_comuna_to_num = dta.dropna(subset=['COMUNA', 'NUMCOMUNA']) \
    .drop_duplicates('COMUNA') \
    .set_index('COMUNA')['NUMCOMUNA'].to_dict()

In [44]:
dta['NUMCOMUNA'] = dta['NUMCOMUNA'].fillna(
    dta['COMUNA'].map(map_comuna_to_num)
)
dta['COMUNA'] = dta['COMUNA'].fillna(
    dta['NUMCOMUNA'].map(map_num_to_comuna)
)

In [45]:
print(dta['NUMCOMUNA'].isna().sum())
print(dta['COMUNA'].isna().sum())

15571
15571

In [43]:
map_comuna_to_num

{'La Candelaria': 10.0,
 'Santa Cruz': 2.0,
 'Popular': 1.0,
 'Guayabal': 15.0,
 'El Poblado': 14.0,
 'Laureles–Estadio': 11.0,
 'Robledo': 7.0,
 'Doce de Octubre': 6.0,
 'Aranjuez': 4.0,
 'Buenos Aires': 9.0,
 'Castilla': 5.0,
 'San Antonio de Prado': 80.0,
 'San Javier': 13.0,
 'Villa Hermosa': 8.0,
 'Belén': 16.0,
 'Manrique': 3.0,
 'La América': 12.0,
 'Altavista': 70.0,
 'San Cristóbal': 60.0,
 'Santa Elena': 90.0,
 'San Sebastián de Palmitas': 50.0}

In [14]:
dta.duplicated().sum()

np.int64(7)

In [16]:
dta = dta.drop_duplicates()